name: Endor Labs - Container Scan and Release

on:
  workflow_dispatch
  
jobs:
  release:
    name: Build and Sign
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Create container
        run: docker build -t endormatt/python-video-game-2:artifact-test .
          
      - name: Get Image Digest to Sign
        run: |
         IMAGE_SHA=$(docker inspect endormatt/python-video-game-2:artifact-test | jq -r '.[].RepoDigests[] | select(contains("nginx"))')
         IMAGE_NAME=endormatt/python-video-game-2
         SIGNING_TARGET="$IMAGE_NAME"@"$IMAGE_SHA"
         echo ARTIFACT="$SIGNING_TARGET" >> $GITHUB_ENV

      - name: Container Sign
        uses: endorlabs/github-action/sign@main
        with:
          namespace: "matt-demo-2"
          artifact_name: ${{ env.ARTIFACT }}
          
      - name: Endor Labs Scan
        uses: endorlabs/github-action@main
        with:
          namespace: "matt-demo-2"
          scan_summary_output_type: "table"
          pr: "false"
          enable_github_action_token: "true"
          scan_dependencies: "true"
          scan_secrets: "true"
          scan_git_logs: "true"
          scan_tools: "true"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Image Digest to Verify
        run: |
         VERIFY_SHA=$(docker inspect endormatt/python-video-game-2:artifact-test | jq -r '.[].RepoDigests[] | select(contains("nginx"))')
         VERIFY_IMAGE_NAME=endormatt/python-video-game-2
         VERIFY_TARGET="$VERIFY_IMAGE_NAME"@"$VERIFY_SHA"
         echo VERIFY_ARTIFACT="$VERIFY_TARGET" >> $GITHUB_ENV
         
      - name: Container verify
        uses: endorlabs/github-action/verify@main
        with:
          namespace: "matt-demo-2"
          artifact_name: ${{ env.VERIFY_ARTIFACT }}
          certificate_oidc_issuer: "https://token.actions.githubusercontent.com"

      - name: Push to Docker Hub
        run: docker push endormatt/python-video-game-2:latest

      - name: Endor Labs Container Scan
        uses: endorlabs/github-action@containers
        with:
          namespace: "matt-demo-2"
          scan_summary_output_type: "table"
          pr: false
          enable_github_action_token: true
          scan_container: true
          scan_dependencies: false
          image: endormatt/python-video-game-2:latest
          project_name: container-python-video-game
          
